$lines = Get-Content 'c:\Users\User\Downloads\128_UNIFIED_MASTER_8D.csv'
$header = $lines[0] -split ','
$fields = $lines[113] -split ','
Write-Output "=== FEVER RAY ROW (line 114) ==="
Write-Output "Profile: $($fields[10])"
Write-Output "MBTI: $($fields[7]) Blood: $($fields[8]) Gender: $($fields[9])"
Write-Output "Element: $($fields[12]) $($fields[13])"
Write-Output "Genre_Release: $($fields[28])"
Write-Output "Genre_Stress_Growth: $($fields[29])"
Write-Output "Genre_Extreme_Growth: $($fields[30])"
Write-Output "BPM: $($fields[31])"
Write-Output "Tension_R_Release: $($fields[32])"
Write-Output "Tension_H_Release: $($fields[33])"
Write-Output "Tension_D_Release: $($fields[34])"
Write-Output "Tension_P_Release: $($fields[35])"
Write-Output "Tension_S_Release: $($fields[36])"
Write-Output "Tension_R_Stress: $($fields[37])"
Write-Output "Tension_H_Stress: $($fields[38])"
Write-Output "Tension_D_Stress: $($fields[39])"
Write-Output "Tension_P_Stress: $($fields[40])"
Write-Output "Tension_S_Stress: $($fields[41])"
Write-Output "Tension_R_Extreme: $($fields[42])"
Write-Output "Tension_H_Extreme: $($fields[43])"
Write-Output "Tension_D_Extreme: $($fields[44])"
Write-Output "Tension_P_Extreme: $($fields[45])"
Write-Output "Tension_S_Extreme: $($fields[46])"
Write-Output "Music_Source_Sounds: $($fields[47])"
Write-Output "Music_Source_Timbre: $($fields[48])"
Write-Output "Vector_8D_G: $($fields[75])"
Write-Output "Vector_8D_Nu: $($fields[76])"
